// API reference, generated by tidy from the /// comments in lib.typ:
//
//   typst compile --root . docs/api.typ docs/api.pdf
#import "@preview/tidy:0.4.3"

#set page(width: 210mm, height: auto, margin: (x: 18mm, y: 16mm), fill: white)
#set text(font: ("Noto Sans", "Noto Sans CJK SC"), size: 10pt, lang: "en")
#set par(justify: false)

#let docs = tidy.parse-module(read("../lib.typ"), name: "vit", require-all-parameters: true)

#text(size: 22pt, weight: 700)[vit] #h(6pt) #text(fill: gray)[API]
#v(4pt)
#eval(docs.description, mode: "markup")
#v(8pt)

#tidy.show-module(
  docs,
  style: tidy.styles.default,
  omit-private-definitions: true,
  show-outline: true,
  sort-functions: none,
)
